### ISSUE TITLE
Ads are not removed

### ISSUE THREAD

**Issue by c12n** [Rov3r/scmusicplus#11]
Tweak version: 24.9.1-1
App Version: 7.56.0
Install method: Trollstore 

Ads are not removed

**Comment by Rov3r** [comment]
Are you using a DNS filter? If so, add ‘ads.soundcloud.com’

If not, you can try to block this domain with either DNS Cloak, or NextDNS.

**Comment by c12n** [comment]
No dns filter

**Comment by Rov3r** [comment]
DNS filter is required
