### ISSUE TITLE
Error of creating directory

### ISSUE THREAD

**Issue by CySxL** [Rov3r/scmusicplus#8]
Just trying the rootless build and I got this error from Sileo: ![image](https://github.com/user-attachments/assets/9e3b55eb-6c04-4702-88b2-098686d76ef4)

**Comment by Rov3r** [comment]
Thanks I’ll look into it

**Comment by Rov3r** [comment]
Fixed in the latest release

**Comment by CySxL** [comment]
Confirmed fixed! Thank you!!
![image](https://github.com/user-attachments/assets/3db924da-4e0c-4205-9e6a-3935e8215ae4)
